#pragma once

#define VERBOSE 0
#define DRAW_CORNERS 0
#define DRAW_TOO_LONG_LINES 0
#define MATCH_PUZZEL 0
#define USE_ADAPTIVE_FEATURE_MARGINE 1
#define USE_ADAPTIVE_FEATURE_SHIFT 1
#define USE_CACHE_IN_SOLVER 1

#define USE_IMAG_EDGES_IN_PUZZEL_DETECTION 0
#define USE_INTRESTING_POINTS_FROM_BACKGROUND 1
#define USE_INTRESTING_POINTS_FROM_BACKGROUND_LINES 1
#define USE_MULTITHREADING_IN_PUZZEL_DETECTION 1
#define USE_BLURED_BACKGROUND_LINES 1
#define TUNE_JOINTS 1

#define ENABLE_SOLVER 1
#define TAKE_INTO_ACCOUNT_EDGES 1
